services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      TZ: "Asia/Tokyo"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    image: ghcr.io/yude/youbine:master
    container_name: youbine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
    depends_on:
      - db
