version: '3'
services:
  app:
    build: https://github.com/yude/switchbot-discord.git#main
    image: ghcr.io/yude/switchbot-discord:main
    volumes:
      - type: bind
        source: ".env"
        target: "/app/.env"
    restart: always
